@echo off
cd backend
echo Creating virtual environment...
python -m venv venv
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing backend dependencies...
pip install -r requirements.txt
echo Starting backend server...
cd app
uvicorn main:app --reload --host 0.0.0.0 --port 8000
